name: Deploy to AWS
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "terraform"

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.COMMON_TOKEN }}
            ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Install Dependencies
        run: cd terraform && ls && npm ci --omit=dev

      - name: Rsync Deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr -delete
          path: ./
          remote_path: /home/${{ secrets.USER }}/
          remote_host: ${{ secrets.HOSTNAME}}
          remote_user: ${{ secrets.USER }}

      - name: SSH in EC2
        env:
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER }}

        run: |
          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '

            #Now we have got the access of EC2 and we will start the deploy .
            cd terraform
            sudo npm install pm2 -g
            sudo pm2 delete all
            sudo pm2 start npm -- start
          '
